version: '3.4'

services: 
  identityaccess:
    build:
      context: .
      dockerfile: ./IdentityAccess/Dockerfile
    image: maddev77/blazorwithkeycloakauth.identityaccess:${PLATFORM:-linux}-${TAG:-latest}
    ports:
      - "8080:8080"
volumes:
  keycloak-data:
  keycloak-conf:


