name: Docker Image CI

on:
  push:
    branches: 
      - features/ci-builds main
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images
      run: docker-compose -f ../../src/docker-compose.yml build
